server:
  port: 8085

spring:
  application:
    name: config-server
  profiles:
    active: native

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/